### ISSUE TITLE
Cannot install denon v2.4.3

### ISSUE THREAD

**Issue by iyuanfang** [denosaurs/denon#107]
I use the command to install denon:

`deno install --allow-read --allow-run --allow-write --allow-net -f -q --unstable https://deno.land/x/denon/denon.ts ` 

but has the error:
`error: TS2367 [ERROR]: This condition will always return 'true' since the types '"main"' and '"master"' have no overlap.
  if (BRANCH !== "master") {
      ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/denon@2.4.3/denon.ts:121:7`

**Comment by qu4k** [comment]
Thanks for spotting this. Should be fixed in c78788f2611bbfd2e31b2d6b2417d14c34d435d3.

You can now install it with:

```bash
$ deno install -qAf --unstable https://deno.land/x/denon@2.4.4/denon.ts
```
