### ISSUE TITLE
denon --upgrade doesn't work

### ISSUE THREAD

**Issue by lastqubit** [denosaurs/denon#108]
denon --upgrade results in:

[*] [main] v2.4.1
[*] [main] Running `deno install -qAf --unstable https://deno.land/x/denon/denon.ts`
error: TS2367 [ERROR]: This condition will always return 'true' since the types '"main"' and '"master"' have no overlap.
  if (BRANCH !== "master") {
      ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/denon@2.4.3/denon.ts:121:7

**Comment by eliassjogreen** [comment]
This is because of a recent release changing the `master` branch to `main` breaking out upgrade function. To upgrade run: `deno install -qAfr --unstable https://deno.land/x/denon@2.4.4/denon.ts` instead.
