### ISSUE TITLE
Denon: command not found

### ISSUE THREAD

**Issue by Moranilt** [denosaurs/denon#117]
**Describe the bug**
I'm using fresh Deno installed. After installing deno i wanted to install a Denon. I went to console(I'm using Bash) and paste 
`deno install -qAf --unstable https://deno.land/x/denon@2.4.4/denon.ts`. After that i've added denon to my global **PATH** and restart the console. 
I've expexcted to see the version of it, but it said to me that command not found.
When i'm trying to call **denon** i've got this:

![error_1](https://user-images.githubusercontent.com/22654219/103091939-c5f75180-4606-11eb-819e-d37c0aaae150.jpg)

**Setup**

- OS: Windows 10 x64
- Deno version: 1.6.2

**Comment by Moranilt** [comment]
I'm sorry. I've ran my terminal as administrator, and it successfully installed and working good. You can just add a line to the documentation, to **run your terminal or console as Administratior**.

**Comment by Moranilt** [comment]
Another one issue.

Denon is not working with **Git Bash**. While using regular Windows powershell - it's working fine, but in Bash - **Denon: command not found**.

**Comment by dennisschott** [comment]
Quickfix: You can use "denon.cmd" instead of "denon". Please also check that "C:\Users\USERNAME\.deno\bin\" is in your Windows "Path" env variable. This is the file where deno + denon is located.

**Comment by Moranilt** [comment]
Yep. **denon.cmd** is **working** for **GitBash**. Thank you!
