### ISSUE TITLE
problem with oak

### ISSUE THREAD

**Issue by m0h0n** [denosaurs/denon#119]
**Describe the bug**
`Uncaught AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)` comes out when edit file with  [oak](https://deno.land/x/oak) middleware

**To Reproduce**
1\. make ts file with [oak](https://deno.land/x/oak) middleware
2\.  run `denon run --allow-net index.ts`
3\.  change `index.ts` file and save it 
4\. See error

**Expected behavior**
run normaly

**Configuration or Project**
dont have any special configuration only `index.ts` and run oak
index.ts
```
import { Application, Router } from "https://deno.land/x/oak/mod.ts";
const port = 8000;

const app = new Application();
const router = new Router();

app.use(router.routes());
app.use(router.allowedMethods());

router.get("/", ({ response }) => {
  response.body = "Hello, world";
});

console.log(`running on port ${port}`);

await app.listen({ port }); // becuse key nad variable are same we put { port } instead of { port: port }
```

**Setup**

- OS: Windows
- Deno version:
``` 
- deno 1.6.3 (release, x86_64-pc-windows-msvc)
v8 8.8.294
typescript 4.1.3
```
- Denon version: `[*] [main] v2.4.4`

**Comment by MustachedNinja** [comment]
This issue is fixed in version 2.4.7, which you can install with `deno install -qAf --unstable https://deno.land/x/denon@2.4.7/denon.ts`
