### ISSUE TITLE
Deno installation error

### ISSUE THREAD

**Issue by manojap** [denosaurs/denon#123]
C:\Users\manoj>deno install --unstable --allow-net https://deno.land/x/denon/denon.ts
Check https://deno.land/x/denon/denon.ts
error: TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
              return pd.url
                        ~~~
    at https://deno.land/std@0.83.0/permissions/mod.ts:17:25

TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
                ? `--allow-${pd.name}=${pd.url}`
                                           ~~~
    at https://deno.land/std@0.83.0/permissions/mod.ts:18:44

Found 2 errors.

I got this error, while running and installing the denon

**Comment by hoangtranson** [comment]
I got same error on Ubuntu.

![Screenshot from 2021-01-25 12-01-55](https://user-images.githubusercontent.com/35447677/105660065-2975e700-5f05-11eb-9148-528e6cd7393a.png)

**Comment by MarvinGronhorst** [comment]
This is the same issue as in #122

**Comment by looselytiedshoelaces** [comment]
How did you guys fix it? I am having same issue right now. Thanks

**Comment by luxwarp** [comment]
Same problem here.

**Comment by jykim1623** [comment]
me too. please check.

**Comment by luxwarp** [comment]
Since deno.land does not have the fix yet you can install denon from github with 
`deno install -qAf --unstable https://raw.githubusercontent.com/denosaurs/denon/main/denon.ts `

**Comment by stall84** [comment]
Thanks @luxwarp  That worked for me perfectly

**Comment by hoangtranson** [comment]
Thanks @luxwarp.

**Comment by CoderNinja123-alt** [comment]
Can anyone explain **why** we are having this issue?

**Comment by eliassjogreen** [comment]
> 
> 
> Can anyone explain **why** we are having this issue?

Incompatible dependencies with the version of deno you are running as the deno core internals are changing and certain features denon uses are unstable, meaning their api is likely to change.

**Comment by manojap** [comment]
try uninstall and reinstall again
