### ISSUE TITLE
I can't install DENON

### ISSUE THREAD

**Issue by abedarev** [denosaurs/denon#155]
PS C:\deno\denon-main> deno --version
deno 1.16.3 (release, x86_64-pc-windows-msvc)
v8 9.7.106.5
typescript 4.4.2
PS C:\deno\denon-main> deno install -qAf --unstable https://deno.land/x/denon/denon.ts
error: TS2345 [ERROR]: Argument of type '"any" | "access" | "create" | "modify" | "remove" | "other"' is not assignable to parameter of type 'FileAction'.
  Type '"other"' is not assignable to type 'FileAction'.
            this.#changes[path].push(kind);
                                     ~~~~
    at https://deno.land/x/denon@2.4.10/src/watcher.ts:150:38
PS C:\deno\denon-main>  **deno install -qAf --unstable https://raw.githubusercontent.com/denosaurs/denon/main/denon.ts**
error: TS2345 [ERROR]: Argument of type '"any" | "access" | "create" | "modify" | "remove" | "other"' is not assignable to parameter of type 'FileAction'.
  Type '"other"' is not assignable to type 'FileAction'.
            this.#changes[path].push(kind);
                                     ~~~~
    at https://raw.githubusercontent.com/denosaurs/denon/main/src/watcher.ts:150:38
PS C:\deno\denon-main> deno install -qAf --unstable https://deno.land/x/denon@2.4.10/denon.ts
error: TS2345 [ERROR]: Argument of type '"any" | "access" | "create" | "modify" | "remove" | "other"' is not assignable to parameter of type 'FileAction'.
  Type '"other"' is not assignable to type 'FileAction'.
            this.#changes[path].push(kind);
                                     ~~~~
    at https://deno.land/x/denon@2.4.10/src/watcher.ts:150:38
PS C:\deno\denon-main>

**Comment by eserozvataf** [comment]
same here. macOS Monterey on arm64


```
❯ deno --version
deno 1.16.3 (release, aarch64-apple-darwin)
v8 9.7.106.5
typescript 4.4.2

❯ deno install -qAf --unstable https://deno.land/x/denon@2.4.10/denon.ts

error: TS2345 [ERROR]: Argument of type '"any" | "access" | "create" | "modify" | "remove" | "other"' is not assignable to parameter of type 'FileAction'.
  Type '"other"' is not assignable to type 'FileAction'.
            this.#changes[path].push(kind);
                                     ~~~~
    at https://deno.land/x/denon@2.4.10/src/watcher.ts:150:38
```

**Comment by nnmrts** [comment]
Yeah, this will be fixed by https://github.com/denosaurs/denon/pull/154 once it's merged.

**Comment by nnmrts** [comment]
In the meantime, you can install denon from my fork, if you want:

```sh
deno install -qAf --unstable https://raw.githubusercontent.com/nnmrts/denon/patch-4/denon.ts
```

**Comment by abedarev** [comment]
Hello! Thank you for your excellent work. Everything works :). Aleksey.Сообщение, полученное 27 нояб. 2021 г. в 3:54 от Nano Miratus ***@***.***>:In the meantime, you can install denon from my fork, if you want:deno install -qAf --unstable https://raw.githubusercontent.com/nnmrts/denon/patch-4/denon.ts—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Warmachine13** [comment]
same issue here 

`error: TS2345 [ERROR]: Argument of type '"any" | "access" | "create" | "modify" | "remove" | "other"' is not assignable to parameter of type 'FileAction'.
  Type '"other"' is not assignable to type 'FileAction'.
            this.#changes[path].push(kind);
                                     ~~~~
    at https://deno.land/x/denon@2.4.10/src/watcher.ts:150:38`

**Comment by ralyodio** [comment]
I also get this error. when will this be fixed?

```
[!] [#0] starting `deno run --allow-all --unstable --no-check ./index.ts`
error: Uncaught (in promise) TypeError: Deno.signal is not a function
          await Deno.signal(s);
                     ^
    at https://deno.land/x/denon@2.4.9/src/daemon.ts:157:22
    at https://deno.land/x/denon@2.4.9/src/daemon.ts:160:10
    at Array.map (<anonymous>)
    at Daemon.onExit (https://deno.land/x/denon@2.4.9/src/daemon.ts:155:31)
    at Daemon.iterate (https://deno.land/x/denon@2.4.9/src/daemon.ts:166:10)
    at iterate.next (<anonymous>)
    at https://deno.land/x/denon@2.4.9/denon.ts:167:20
```

**Comment by Xzoky174** [comment]
This has been opened for 19 days. How long will it take to be fixed??

**Comment by jeremythille** [comment]
> In the meantime, you can install denon from my fork, if you want: deno install -qAf --unstable https://raw.githubusercontent.com/nnmrts/denon/patch-4/denon.ts

The installation of your fork works (thanks), but then I'm getting :

> 'denon' is not recognized as an internal or external command, operable program or batch file.

Of course I've tried closing and restarting my terminal.

**Comment by nnmrts** [comment]
> This has been open for 19 days. How long will it take to be fixed??

@Xzoky174 
It **is** fixed by https://github.com/denosaurs/denon/pull/154 and installable. The great thing about deno in comparison to node.js and npm is that you don't have to switch between packages in this case. If you take a look at the [`uprade`](https://github.com/denosaurs/denon/blob/main/src/cli.ts#L88) command, you'll see that once my PR gets merged and it's part of denon "officially", you can just run `denon upgrade` to get an official denon version from https://deno.land/x/denon again.

Also, small reminder that it's December and that most people in the western world currently are busy buying gifts for and having a tranquil time with their family. If you absolutely need an "official" fix: I wouldn't expect one before mid January, to be honest.

I've also just made a tag and a release on my fork, which means you can now install it from [jsdelivr](https://cdn.jsdelivr.net/) instead of https://raw.githubusercontent.com (which was never meant to be used like this). Should be faster as well. Install like this:

```sh
deno install -qAf --unstable https://cdn.jsdelivr.net/gh/nnmrts/denon@2.4.10.patch-4/denon.ts
```

**Comment by reven404** [comment]
deno 1.17.0
```
deno --version
```
deno 1.17.0 (release, aarch64-apple-darwin)
v8 9.7.106.15
typescript 4.5.

```
deno install -qAf --unstable https://deno.land/x/denon/denon.ts
```
error: TS2345 [ERROR]: Argument of type '"any" | "access" | "create" | "modify" | "remove" | "other"' is not assignable to parameter of type 'FileAction'.
  Type '"other"' is not assignable to type 'FileAction'.
            this.#changes[path].push(kind);
                                     ~~~~
    at https://deno.land/x/denon@2.4.10/src/watcher.ts:150:38
