### ISSUE TITLE
Support for outputting the bundle to a file

### ISSUE THREAD

**Issue by RobertAKARobin** [denosaurs/denon#28]
Deno will create an executable file with e.g. `deno bundle src.ts > dist.ts`. It looks like this package currently supports bundling, but not really outputting the bundle to a file.

**Comment by ManuelRauber** [comment]
Just use something like this:

```json
"bundle": {
  "cmd": "deno bundle src/index.ts my-bundle.js",
  "desc": "Bundles the server for deployment.",
  "tsconfig": "tsconfig.json"
}
```
