### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by hasri20** [denosaurs/denon#45]
error: TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    await Deno.symlink(originSrcFilePath, dest, {
                                                
    at https://deno.land/std@0.52.0/fs/copy.ts:117:49

TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    Deno.symlinkSync(originSrcFilePath, dest, {
                                              
    at https://deno.land/std@0.52.0/fs/copy.ts:141:47

TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    await Deno.symlink(src, dest, {
                                  
    at https://deno.land/std@0.52.0/fs/ensure_symlink.ts:33:35

TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    Deno.symlinkSync(src, dest, {
                                
    at https://deno.land/std@0.52.0/fs/ensure_symlink.ts:65:33

Found 4 errors.

i'm using xubuntu 20.04

**Comment by Qu4k** [comment]
Hi 👋🏻 ,
What deno version are you using?
(`deno —version` to check)

**Comment by hasri20** [comment]
> Hi 👋🏻 ,
> What deno version are you using?
> (`deno --version` to check)

![2020-05-23_01-09](https://user-images.githubusercontent.com/19608381/82696886-2b124f80-9c92-11ea-8842-9c24b03d9540.png)
i'm using v 1.0.0

**Comment by Qu4k** [comment]
There were some breaking updates with deno v1.0.1, you should update your deno executable with `deno upgrade`. After the update everything should work just fine ✅

**Comment by hasri20** [comment]
> There were some breaking updates with deno v1.0.1, you should update your deno executable with `deno upgrade`. After the update everything should work just fine

![2020-05-23_01-15](https://user-images.githubusercontent.com/19608381/82697326-e89d4280-9c92-11ea-94c8-430d2b7ad289.png)
work like a charm! thank you

**Comment by calleufuzi** [comment]
> There were some breaking updates with deno v1.0.1, you should update your deno executable with `deno upgrade`. After the update everything should work just fine ✅

Work fine for me too! thx
