### ISSUE TITLE
typo in scripts.ts | inspect / inspect-brk

### ISSUE THREAD

**Issue by Tnifey** [denosaurs/denon#46]
Hello :) 
there is an error with `inspect` and `inspect-brk` in scripts config

```bash
$ denon start
[denon] v2.0.0
[denon] starting `deno run --allow-all --config tsconfig.json --inspect=localhost:9229} src/main.ts`
error: Invalid value for '--inspect=<HOST:PORT>': invalid IP address syntax
```

there is additional braces at end of pushed strings

https://github.com/denosaurs/denon/blob/ae50c344d0197da967081e71a4a0060a20a27db5/src/scripts.ts#L167

https://github.com/denosaurs/denon/blob/ae50c344d0197da967081e71a4a0060a20a27db5/src/scripts.ts#L170

**Comment by Qu4k** [comment]
Thanks, it is now fixed. 👍
