### ISSUE TITLE
Bad resource ID

### ISSUE THREAD

**Issue by ansonfoong** [denosaurs/denon#47]
This seems to happen a lot when I ctrl + s and the process restarts, any idea on why?
```
error: Uncaught BadResource: Bad resource ID
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async runStatus ($deno$/process.ts:22:15)
    at async Daemon.monitor (https://deno.land/x/denon/src/daemon.ts:63:15)
```

My .denon.json file:

```
{
  "scripts": {
    "start": {
      "cmd": "deno run ./src/index.ts",
      "desc": "Starting up Client...",
      "allow": [
        "env", "hrtime", "read", "net"
      ],
      "unstable": true
    },
    "test": {
      "cmd": "deno test tests/tests.ts",
      "desc": "Running tests...",
      "allow": [
        "env", "read"
      ]
    }
  }
}
```

**Comment by Qu4k** [comment]
I am not able to reproduce the issue but since the error is generated by a cleanup part of the code I can try to make it more forgiving. Processes in deno are still considered `--experimental` so handling them can be a bit tricky.

**Comment by Qu4k** [comment]
In 0e900ad360c34383da7dbaace966d7c13b5e4129 I patched the status await function. Upgrade your `denon` exe with `denon --upgrade` and let me know if the issue persists 😄

**Comment by ansonfoong** [comment]
Seems to be good now. Thank you
