### ISSUE TITLE
Support for sequential scripts

### ISSUE THREAD

**Issue by sean-clarke** [denosaurs/denon#50]
I am using denon inside a Docker container build with the hayd deno image and would like to support file watching/restart that rebundles my client scripts then runs server.ts... however, I don't believe I am able to do this without passing multiple cmds into my denon.json script... If I use multiple scripts, denon hangs on the first one called, and if I pre bundle, then I am only getting file watching/restart on my server-side code.

**Comment by Qu4k** [comment]
Correct me if I am wrong but you are basically asking for parallel daemonized processes support? This could actually be a very useful feature. Something like:
```jsonc
{
  "scripts": {
    "run": ["first command", "second command"]
  }
}
```
that can be run with `denon run` would suit your needs?

**Comment by ManuelRauber** [comment]
AFAIK `&&` is not to let something run in parallel in bash, but in sequential. That's how I've normally done my node.js scripts, when to deploy something:

As an example: 

```json
"scripts": {
  "deploy": "cp config.ts dist.config.ts && cp README.md dist/README.md && tsc"
}
```

If you wanted to run something in parallel, you could use concurrently in Node.js (do we need a concurrently in Deno? :-))

I'd rather prefer to have a sequential support in denon rather than a parallel support (at first).

**Comment by r1oga** [comment]
Would love this feature too!
Currently as a not so elegant workaround I am defining 2 different `denon.json` config files. Then I run `denon` in 2 different terminal  with the `--config` option. Ex:
- `denon -c src/denon.json build`: watches `src/index.ts` and rebuilds on change
- `denon -c build/denon.json start`: watches `build/index.js` and runs on change (i.e after rebuild)

**Comment by Qu4k** [comment]
[Just pushed](https://github.com/denosaurs/denon/commit/a4568fe34ce5f400f0d29e39cbc696740baee901) a branch with a basic implementation of this feature, you can take a look using this installation command:

```
$ deno install --allow-read --allow-run --allow-write --allow-net -f --unstable https://deno.land/x/denon@feat-sequential-scripts/denon.ts
```
Please let me know if you have any feedback on how this feature should be implemented further.  😊
