### ISSUE TITLE
Inspect Config Doc is Incorrect

### ISSUE THREAD

**Issue by ebebbington** [denosaurs/denon#53]
The documentation outlines you can use `inspect in your config`:

```
"inspect": "localhost:1234"
```

But Deno is saying `localhost` is not a valid host to use. If we switch `localhost` with `127.0.0.1` (or similar), it works:

```
"inspect": "127.0.0.1:1234"
```

**How To Replicate**
Add `"inspect": "localhost:9229",` to a script in your config and run

**Comment by Qu4k** [comment]
Thanks for spotting that
