### ISSUE TITLE
Tests not running anymore?

### ISSUE THREAD

**Issue by edenprojectde** [denosaurs/denon#55]
Just updated, and it seems deno test is not run anymore, and as mentioned here https://github.com/denosaurs/denon/issues/50 it's not possible to have &/&& to run multiple commands one after another?

Maybe adding a "test" to a scripts-object would be useful. (this has been an option before i updated though it was in the main config; seems like it isn't mentioned in the README anymore, has it been removed?)

**Comment by Qu4k** [comment]
Closing in favour of #50 , probably going to be adjusted when `2.1` releases
