### ISSUE TITLE
Support YAML for scripts

### ISSUE THREAD

**Issue by hazae41** [denosaurs/denon#60]
Like Velocyraptor does

**Comment by eliassjogreen** [comment]
There already is support for yaml configuration. It uses the same format as the json configuration format. [Example](https://www.github.com/denosaurs/denon/tree/master/templates%2Fdenon.yml)

**Comment by Qu4k** [comment]
We should improve readme to specify that YAML format is supported

**Comment by hazae41** [comment]
> We should improve readme to specify that YAML format is supported

That's why I thought it was not supported

**Comment by Qu4k** [comment]
Fixed in 176ce15fdef36f7cfcd0af53b4e11a3fa68a6f5b, thanks @hazae41
