### ISSUE TITLE
denon v2.1.0 CLI commands errors

### ISSUE THREAD

**Issue by omaralmgerbie** [denosaurs/denon#61]
**an issue while using denon CLI commands**
im trying to run denon --init and it responds with an error 

> PS D:\deno\denon> denon --init
> ️⚠️  Deno requests network access. Grant? [g/d (g = grant, d = deny)] g
> [denon] fetching template from https://deno.land/x/denon@2.1.0/templates/denon.json
> [denon] `denon.json` is not a denon template. All templates are available on https://deno.land/x/denon@2.1.0/templates/

and when i try to upgrade this error pops out 

**Screenshots**
![denon](https://user-images.githubusercontent.com/28146110/83973896-beca5980-a8e9-11ea-8408-c7812ec53039.PNG)

**Setup**

-   OS: (windows,)
-   Deno version: (`1.0.3`)
-   Denon version: (`V2.1.0`)

**Comment by Qu4k** [comment]
Thanks for spotting this issue.  Working on a fix right now

**Comment by omaralmgerbie** [comment]
yeah i did that and still having the same issues.

**Comment by elnobun** [comment]
# ISSUE STILL NOT FIXED!

## This is the Error in console after `denon --init`

```
[denon] v2.1.0
[denon] fetching template from https://deno.land/x/denon@2.1.0/templates/denon.json
```

It appears `denon` is fetching template from the wrong page.

The template path is supposed to be fetched from here here:

```
https://deno.land/x/denon/templates/
```

---

## FIX
For the moment, after installing Denon,  you can create the `denon.json` file yourself, and it will work as expected.

**Comment by Qu4k** [comment]
The problem is now related to incorrect tagging on deno.land/x/, probably going to release 2.1.1 so that tags can align

**Comment by Qu4k** [comment]
`deno install --allow-read --allow-run --allow-write --allow-net -f --unstable https://deno.land/x/denon@v2.2.0/denon.ts` to install the latest version.  Hoping the deno gods that tags are now aligned correctly.

**Comment by omaralmgerbie** [comment]
ok its fixed for now 
thank you! 🤗
