### ISSUE TITLE
Absolute path monitoring

### ISSUE THREAD

**Issue by timonson** [denosaurs/denon#66]
Passing an absolute path on Linux to the `match` property doesn't work. It will ignore file changes in this path:

```json
  "watcher": {
    "interval": 350,
    "exts": ["ts", "html"],
    "match": ["/home/user/javascript/myWebComponents/**/*.*"],
    "skip": ["*/.git/*"]
  }
```

It would make things easier if the *watcher* would accept absolute paths.

**Comment by Qu4k** [comment]
Adding this to `2.2.0` milestone, thanks @timonson

**Comment by timonson** [comment]
Amazing, ty @Qu4k ! Do you want me to close this issue?

**Comment by Qu4k** [comment]
Nope, this issue can be a reminder for us developers, or maybe a contributor (👀), to implement this feature
