### ISSUE TITLE
Deno requests network access. Grant?

### ISSUE THREAD

**Issue by Bidek56** [denosaurs/denon#68]
**Describe the bug**
With each run of denon, I get this question:

️`⚠️  Deno requests network access. Grant? [g/d (g = grant, d = deny)]`

**To Reproduce**
1\. `denon  --allow-net`

**Expected behavior**
--allow-net should avoid this question

**Setup**

-   OS:  Ubuntu 20.04, WSL2
-   Deno version: 1.1.1
-   Denon version: 2.2.0

**Comment by Qu4k** [comment]
After the 2.2.0 update we added network permissions to handle template download.  You should probably reinstall denon:
```
$ deno install --allow-read --allow-run --allow-write --allow-net -f --unstable https://deno.land/x/denon@v2.2.0/denon.ts
```
