### ISSUE TITLE
Allow flag type warning

### ISSUE THREAD

**Issue by kevinhassan** [denosaurs/denon#69]
**Describe the bug**
I used the allow flag to specification (see the documentation : [here](https://github.com/denosaurs/denon#permissions)), but the linter prints warning on the `boolean` type for the allow flag`"env": true` due to deno flag type (`Array<String>` | `Object` --> [schema.json](https://deno.land/x/denon/schema.json) )

**To Reproduce**
1\. Go to `denon.json`
2\. Scroll down to `env: true`
3\. See the warning: `Incorrect type. Expected "string".`

**Expected behavior**
No linter warning

**Configuration or Project**
```json
{
  "$schema": "https://deno.land/x/denon/schema.json",
  "allow": {
    "net": true, 
    "env": true, 
    "read": true, 
    "write": true, 
    "plugin": true
  },
  "unstable": true,
  "inspect": "127.0.0.1:9229",
  "scripts": {
    "start": {
      "cmd": "deno run index.ts",
      "desc": "run my deno server file",
      "lock": "lock.json"
    }
  }
}
```

**Screenshots**

**Setup**

-   OS: macOS v10.15.5
-   Deno version: 1.1.1
-   Denon version: v2.1.0

**Comment by Qu4k** [comment]
Thanks for spotting that, will change schema asap
