### ISSUE TITLE
[doc] Clarify permissions format

### ISSUE THREAD

**Issue by jsejcksn** [denosaurs/denon#70]
In [README#permissions](https://github.com/denosaurs/denon/blob/d314ca5cf039b6c31376c163ad80f362c6b82277/README.md#permissions), it shows this example:

> Permission can be granted to child processes.
> ```jsonc
> {
>   // globally applied to all scripts
>   "allow": {
>     "read": "/etc", // --allow-read=/etc
>     "env": true     // --allow-env
>   },
> 
>   "scripts": {
>     "start": {
>       "cmd": "deno run app.ts",
>       "desc": "Run the main server.",
> 
>       "allow": [
>         "run", // --allow-run
>         "net", // --allow-net
>       ]
>     }
>   }
> }
> ```

but it doesn't make clear which format/s is/are acceptable. For example:

1. Does the top-level `allow` key accept an array of boolean values in addition to the object format?
2. Does each script's `allow` key accept an object value (like the top-level example) with keys' values corresponding to granular permission values?
3. How does the object format work if a permission has multiple values? Should an array be supplied, like so?

```jsonc
{
  "allow": {
    "read": [
      "/etc",
      "/opt"
    ], // --allow-read=/etc,/opt
    "env": true // --allow-env
  }
}
```

**Comment by Qu4k** [comment]
> How does the object format work if a permission has multiple values? Should an array be supplied, like so?
> ```jsonc
> {
>   "allow": {
>     "read": [
>       "/etc",
>       "/opt"
>     ], // --allow-read=/etc,/opt
>     "env": true // --allow-env
>   }
> }
> ```

For now you have to specify multiple values inside a single string, like so:

```jsonc
{
  "allow": {
    "read": "/etc,/opt"
  }
}
```
