### ISSUE TITLE
Cannot find name 'env' in denon.config.ts

### ISSUE THREAD

**Issue by hylerrix** [denosaurs/denon#71]
**Describe the bug**

As screenshots below:

**Configuration or Project**

```
import { DenonConfig } from "https://deno.land/x/denon/mod.ts"
export { config as env } from "https://deno.land/x/dotenv/mod.ts"

const config: DenonConfig = {
  env: env(), // Cannot find name 'env'
  scripts: {
    start: {
      cmd: "deno run src/server.ts",
      desc: "start from server.ts file",
      watch: true,
      env: {
        PORT: Deno.env.get('PORT') || "8080",
      },
      allow: [
        "env",
        "net",
        "read",
        "write",
        "plugin",
      ],
      unstable: true
    },
  },
  logger: {
    debug: true,
  },
  watcher: {
    exts: ["ts", "json", "ini"],
    skip: ["super_duper_secret/*"],
  },
}

export default config
```

**Screenshots**

![](https://user-images.githubusercontent.com/19285461/86988608-34686480-c1cb-11ea-960c-123b1c907b00.png)

**Setup**

-   OS: (e.g. macOS, windows, linux) MacOS
-   Deno version: (`deno version`) 1.0.5
-   Denon version: (`denon --version`) v2.2.0

**Additional context**

Why `denon --version` need to compile `denon.config.ts` instead of return version number directly?

**Comment by Qu4k** [comment]
You should change `export` to `import` in line 2

**Comment by Qu4k** [comment]
Changed the documentation, thanks for pointing this out 🌟
