### ISSUE TITLE
Denon does not watch files in subfolders.

### ISSUE THREAD

**Issue by Sameerkash** [denosaurs/denon#73]
**Describe the bug**
denon does not seem to be watching files in subfolders. As I observed my server would restart if I changed files in the root of the folder but not in subfolders.

Here's my tree
.
├── controller
│   ├── post_controller.ts
│   └── user_controller.ts
├── denon.json
├── deps.ts
├── mod.ts
├── models
│   ├── post.ts
│   └── user.ts
├── routes
│   └── routes.ts
└── utils
    └── db.ts

**Expected behavior**
Changing mod.ts, Denon.json, and deps.ts restarts the server but changing any other file does not. 

**Setup**

-   OS: Ubuntu 20.04 on WSL2 
-   Deno version: 1.1.3
-   Denon version: 2.2.0

denon.json
```
{
  "$schema": "https://deno.land/x/denon/schema.json",
  "scripts": {
    "dev": "deno  run --allow-net --allow-read --unstable --allow-write --allow-plugin  mod.ts",
    "cache": "deno cache deps.ts",
  }
}
```

**Comment by Qu4k** [comment]
This is related to #57.  You can try to use the `legacy` option in the configuration, under the `watcher` options. See more [here](https://github.com/denosaurs/denon#watcher).

**Comment by Sameerkash** [comment]
Thank you for the response, didn't see that. Also, the global install of Denon failed on windows with a cannot find path error, know any fixes? Hence shifted to WSL ubuntu.

I'll be closing this.

**Comment by Sameerkash** [comment]
Actually this did not solve my problem, setting `legacy` to `true` just throws an error and does not start the server.

**Comment by clianor** [comment]
I have the same problem.

**Comment by qu4k** [comment]
Unfortunately WLS2 seems to have many compatibility problems with how deno handles the filesystem.  We will at some solutions in the coming days, but since we don't have access to a WLS2 enabled windows PC it will take some time.  

If in the meantime you come up with a solution feel free to open a or.

**Comment by Sameerkash** [comment]
@qu4k  Sure, I'll try to take a look into the issue,  But I'm not too thorough. It'd be a help if you could give me some pointers where I can look.

**Comment by qu4k** [comment]
In the code I think all the logic you need to work with is on the `src/watcher.ts` file.

`denoWatch()` is the default watcher.
`legacyWatcher()` well, it's the legacy one haha.

I would suggest to you [this](https://dev.to/otanriverdi/let-s-explore-deno-by-building-a-live-reloader-j47) dev.to article that explains (I haven't proofread) how a basic file watcher works. And see if it works on your machine.

If you come up with a solution without touching denon's code you can open a repo and link it here and I will be happy to adapt it to code base.

**Comment by aaronwlee** [comment]
error: Uncaught TypeError: Cannot read property 'push' of undefined
          this.#changes[path].push("modify");
                              ^
    at Watcher.legacyWatch (watcher.ts:222:31)

that legacy is not working...

```json
{
  "$schema": "https://deno.land/x/denon/schema.json",
  "scripts": {
    "dev": {
      "env": {
        "DEVElOPMENT": "true"
      },
      "cmd": "deno run server.tsx",
      "desc": "run development server",
      "tsconfig": "tsconfig.json",
      "unstable": true,
      "allow": ["read", "write", "env", "net"]
    }
  },
  "watcher": {
    "paths": ["./controllers/", "./view/"],
    "legacy": true
  },
  "logger": {

  }
}
```

**Comment by qu4k** [comment]
>```error: Uncaught TypeError: Cannot read property 'push' of undefined
> this.#changes[path].push("modify");
>                     ^
> at Watcher.legacyWatch (watcher.ts:222:31)
>```

Thanks for pointing this out.  I am pushing a commit to fix this issue asap 😄
