### ISSUE TITLE
Why do programs get stuck after I use the inspectbrk command？

### ISSUE THREAD

**Issue by ToWeLong** [denosaurs/denon#78]
deno: 1.2.0
v8: 8.5.216
typescript: 3.9.2

![image](https://user-images.githubusercontent.com/41502558/87631775-a8c27b00-c76a-11ea-9789-6e2177ba05fd.png)

**Comment by qu4k** [comment]
`inspectBrk` stands for inspect break.  Taking a look at the [deno manual](https://deno.land/manual/tools/debugger#chrome-devtools):
> use the `--inspect-brk` flag to break execution on the first line
