### ISSUE TITLE
denon --init throws error "`denon.json` is not a denon template."

### ISSUE THREAD

**Issue by thecodeholic** [denosaurs/denon#84]
**Describe the bug**
I have deno version 1.2.2 and installed denon version 2.3.0.
When I run `denon --init` from command line I get the following error.
![image](https://user-images.githubusercontent.com/4627922/89251734-d80d2f00-d628-11ea-9ae5-8e11bfec3d00.png)

**To Reproduce**
1\. Install deno version 1.2.2
2\. Install denon by running the following code `deno install --allow-read --allow-run --allow-write --allow-net -f --unstable https://deno.land/x/denon@v2.3.0/denon.ts`
3\. Run from command line `denon --init`
4\. See error

**Expected behavior**
It should generate `denon.json` file

**Setup**

-   OS: Windows 10
-   Deno version: (`1.2.2`)
-   Denon version: (`2.3.0`)

**Comment by WhoAdarshPandya** [comment]
> **Describe the bug**
> I have deno version 1.2.2 and installed denon version 2.3.0.
> When I run `denon --init` from command line I get the following error.
> ![image](https://user-images.githubusercontent.com/4627922/89251734-d80d2f00-d628-11ea-9ae5-8e11bfec3d00.png)
> 
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1\. Install deno version 1.2.2
> 2\. Install denon by running the following code `deno install --allow-read --allow-run --allow-write --allow-net -f --unstable https://deno.land/x/denon@v2.3.0/denon.ts`
> 3\. Run from command line `denon --init`
> 4\. See error
> 
> **Expected behavior**
> It should generate `denon.json` file
> 
> **Setup**
> 
> -   OS: Windows 10
> -   Deno version: (`1.2.2`)
> -   Denon version: (`2.3.0`)
> 
> 

Same happened with me

**Comment by qu4k** [comment]
Thanks for pointing this out. This is probably an issue related to the registry. I'll investigate

**Comment by eliassjogreen** [comment]
Probably due to it fetching from `denon@master` which no longer works?
