### ISSUE TITLE
info.ts missing from egg.json for denon 2.3.1

### ISSUE THREAD

**Issue by tranzystorek-io** [denosaurs/denon#88]
**Describe the bug**
Seems like the `egg.json` file is missing the `info.ts` file. This makes denon 2.3.1 fail to install from nest.land

**To Reproduce**

1. Try to install denon 2.3.1 from nest

**Expected behavior**
Denon installs successfully

**Actual behavior**
Denon fails to install with missing info.ts file (404 Not Found)

**Comment by qu4k** [comment]
Thanks for pointing this out, a fix is on its way 🚂
