### ISSUE TITLE
denon command not found on linux

### ISSUE THREAD

**Issue by mejdi14** [denosaurs/denon#93]
**Describe the bug**
runing the command 'denon run' retrun 'command not found' right after installing denon

**To Reproduce**
1\. installing denon
2\. try to run the app using denon
3\. See error 'command denon not found'

**Expected behavior**
the app starts

**Configuration or Project**
just a fresh install 

**Screenshots**
![Screenshot from 2020-08-22 11-53-20](https://user-images.githubusercontent.com/22161913/90954713-aab8e180-e46e-11ea-92d5-def125a0bd42.png)

**Setup**

-   OS: (linux ubuntu 20.4)
-   Deno version: (`1.3.0`)
-   Denon version: (`2.3.2`)

**Comment by BunnyTheLifeguard** [comment]
Same for Manjaro 20.1 / Deno 1.3.1 / Denon 2.3.2

**Comment by qu4k** [comment]
@mejdi14 & @BunnyTheLifeguard do other tools installed with `deno install` work?

**Comment by BunnyTheLifeguard** [comment]
> @mejdi14 & @BunnyTheLifeguard do other tools installed with `deno install` work?

That's interesting. Tried [Velociraptor](https://github.com/umbopepato/velociraptor) aswell and the same problem occurs. So a problem with Deno itself then, I guess?

**Comment by BunnyTheLifeguard** [comment]
Alright, so like I said earlier the commands are working right now, but I get Type errors as described in #74 

Here are mine:
```
$ denon help
error: TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    await Deno.symlink(originSrcFilePath, dest, {
                                                
    at https://deno.land/std@0.63.0/fs/copy.ts:117:49

TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    Deno.symlinkSync(originSrcFilePath, dest, {
                                              
    at https://deno.land/std@0.63.0/fs/copy.ts:141:47

TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    await Deno.symlink(src, dest, {
                                  
    at https://deno.land/std@0.63.0/fs/ensure_symlink.ts:32:35

TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    Deno.symlinkSync(src, dest, {
                                
    at https://deno.land/std@0.63.0/fs/ensure_symlink.ts:64:33

TS2554 [ERROR]: Expected 2 arguments, but got 3.
  await Deno.writeTextFile(filePath, jsonString, {
                                                 
    at https://deno.land/std@0.63.0/fs/write_json.ts:37:50

TS2554 [ERROR]: Expected 2 arguments, but got 3.
  Deno.writeTextFileSync(filePath, jsonString, {
                                               
    at https://deno.land/std@0.63.0/fs/write_json.ts:52:48

Found 6 errors.
```

**Comment by qu4k** [comment]
I should probably add a FAQ / Troubleshooting section in the README.

For now, since @mejdi14 has reacted with a 👍 on @BunnyTheLifeguard solution I can mark this issue as resolved. 🌈

**Comment by spancavil** [comment]
Sorry that does not work for me. I added to PATH with echo and nothing.
