### ISSUE TITLE
Error TS2790: The operand of a 'delete' operator must be optional with latest Deno+Denon

### ISSUE THREAD

**Issue by quaos** [denosaurs/denon#94]
**Describe the bug**
Failed to run latest denon (2.3.2) with deno 1.3.2 in Windows 10 (not tried with Linux/MacOS yet)

**To Reproduce**
1\. Install latest deno 1.3.2, and denon 2.3.2
2\. Set PATH variable to include location of `denon.cmd` script
2\. Open command prompt
3\. Enter: `denon --version`
4\. See error

**Expected behavior**
Deno should be able to compile and run denon, showing denon version

**Configuration or Project**
N/A

**Screenshots**
```cmd
>deno --version
deno 1.3.2
v8 8.6.334
typescript 4.0.2

>denon --version
error: TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete g.scripts;
           ~~~~~~~~~
    at https://deno.land/x/denon@2.3.2/src/runner.ts:132:12

>deno info --no-check --unstable https://deno.land/x/denon@2.3.2/denon.ts
error: Uncaught SyntaxError: The requested module './levels.ts' does not provide an export named 'LevelName'

```

**Setup**

-   OS: Windows10 64-bit
-   Deno version: 1.3.2
-   Denon version: 2.3.2

**Additional context**

denon.cmd file:
```batch
% generated by deno install %
@deno.exe "run" "--allow-read" "--allow-write" "--allow-net" "--allow-run" "--quiet" "--unstable" "https://deno.land/x/denon@2.3.2/denon.ts" %*
```

**Comment by qu4k** [comment]
Thanks for the report, a fix is on its way. ⚒️

**Comment by qu4k** [comment]
Added support to deno 1.3.0 🎉 

Please open another issue if you find any other problem with this release.
