### ISSUE TITLE
Unable to load schema

### ISSUE THREAD

**Issue by seahindeniz** [denosaurs/denon#98]
**Describe the bug**
I just installed the Deno and Denon and started a new project without executing/running anything. I have set up my env. and installed the Deno VSCode extension.
After installing Deno, Denon and creating the denon.json file, the `$schema` entry shows the following error
`
Unable to load schema from 'https://deno.land/x/denon/schema.json': Request vscode/content failed unexpectedly without providing any details.(768)
`

**To Reproduce**
1\. Fresh installation
2\. Create a new project and JSON file
3\. Paste configuration copied from [here](https://denosaurs.land/docs/denon/configuration/templates)
4\. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/5789670/92710074-24523a00-f360-11ea-9eee-66d02918508d.png)
![image](https://user-images.githubusercontent.com/5789670/92710737-b6f2d900-f360-11ea-9367-18b71e95675b.png)

**Setup**

- OS: Ubuntu 20 on WSL2
- Deno version: 1.3.3
- Denon version: 2.3.3

**Additional context**
If I add the raw schema URL to the denon.json, it works

![image](https://user-images.githubusercontent.com/5789670/92711073-f7eaed80-f360-11ea-807b-bcd0d3e20814.png)

**Comment by qu4k** [comment]
Mhn. Probably I should start defaulting to the versioned import: `https://deno.land/x/denon@2.4.0/schema.json`.

**Comment by eliassjogreen** [comment]
Are you using a proxy? It seems like that could interfere with schema importing in vscode. According to [stackoverflow](https://stackoverflow.com/questions/49056000/all-of-my-json-files-have-problems-loading-reference-schema-from-schemastore-az) you should be able to solve this with editing the user settings file to have `"http.proxySupport": "off"`.
